name: Terraform & App CI 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform Validate & Plan'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - - name: Terraform Plan
  run: |
    terraform plan \
      -var 'public_subnet_id=subnet-12345678' \
      -var 'key_name=my-key' \
      -var 'security_group_id=sg-12345678' \
      -var 'ec2_role_name=my-ec2-role' \
      -var 'private_subnet_ids=["subnet-87654321"]' \
      -var 'db_security_group_id=sg-87654321' \
      -var 'db_name=mydb' \
      -var 'db_username=admin' \
      -var 'db_password=changeme' \
      -var 'ec2_instance_id=i-12345678' \
      -var 'vpc_id=vpc-12345678' \
      -var 'my_ip_cidr=1.2.3.4/32' \
      -var 'bucket_name=my-unique-bucket-123' \
      -var 'project_tag=RealEstateCloud' \
      -var 'environment=dev' \
      -var 'vpc_cidr_block=10.0.0.0/16' \
      -var 'public_subnet_cidr=10.0.1.0/24' \
      -var 'availability_zone=eu-west-1a' \
      -var 'vpc_name=free-tier-vpc' \
      -var 'subnet_name=free-tier-public-subnet-1' \
      -var 'db_instance_class=db.t3.micro' \
      -var 'private_subnet_cidr=10.0.2.0/24' \
      -var 'db_allocated_storage=20' \
      -var 'db_engine_version=15.4'
  working-directory: terraform

  docker-build:
    name: 'Build Docker Image (Safe)'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t real-estate-app .

  app-test:
    name: 'FastAPI App Tests'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt pytest

      - name: Run tests
        run: pytest  

