name: Terraform & App CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print AWS env (debug)
        run: |
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Clean Terraform cache
        run: rm -rf .terraform .terraform.lock.hcl
        working-directory: terraform

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: |
          terraform plan \
            -var 'aws_region=eu-west-1' \
            # … tus otros -var aquí …
            -var 'db_engine_version=15.4'
        working-directory: terraform

  docker-build:
    name: Build Docker Image (Safe)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug workspace (ver estructura)
        run: |
          echo ">>> pwd: $PWD"
          echo ">>> root files:"
          ls -1 .
          echo ">>> app/ files:"
          ls -1 app

      - name: Build Docker image
        run: |
          docker build \
            --file app/Dockerfile \    # ruta al Dockerfile dentro de app/
            --tag fastapi-docker-app \
            app                        # contexto = carpeta app

  app-test:
    name: FastAPI App Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt pytest

      - name: Run tests
        run: |
          export PYTHONPATH=app       # para que `import app.main` funcione
          pytest tests               # lee los tests desde tests/






