name: Terraform CI

on:
  push:
    branches:
      - main    # Ejecuta este workflow en cada push a la rama main
  pull_request:  # También ejecuta cuando se hace un Pull Request hacia cualquier rama

jobs:
  terraform:
    name: 'Terraform Validate & Plan'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform
