name: Terraform & App CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform Validate & Plan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: |
          terraform plan \
            -var "public_subnet_id=${{ secrets.PUBLIC_SUBNET_ID }}" \
            -var "key_name=${{ secrets.KEY_NAME }}" \
            -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
            -var "ec2_role_name=${{ secrets.EC2_ROLE_NAME }}" \
            -var "private_subnet_ids=[\"${{ secrets.PRIVATE_SUBNET_ID }}\"]" \
            -var "db_security_group_id=${{ secrets.DB_SECURITY_GROUP_ID }}" \
            -var "db_name=${{ secrets.DB_NAME }}" \
            -var "db_username=${{ secrets.DB_USERNAME }}" \
            -var "db_password=${{ secrets.DB_PASSWORD }}" \
            -var "ec2_instance_id=${{ secrets.EC2_INSTANCE_ID }}" \
            -var "vpc_id=${{ secrets.VPC_ID }}" \
            -var "my_ip_cidr=${{ secrets.MY_IP_CIDR }}" \
            -var "bucket_name=${{ secrets.BUCKET_NAME }}" \
            -var "project_tag=RealEstateCloud" \
            -var "environment=dev" \
            -var "vpc_cidr_block=10.0.0.0/16" \
            -var "public_subnet_cidr=10.0.1.0/24" \
            -var "availability_zone=eu-west-1a" \
            -var "vpc_name=free-tier-vpc" \
            -var "subnet_name=free-tier-public-subnet-1" \
            -var "private_subnet_cidr=${{ secrets.PRIVATE_SUBNET_CIDR }}" \
            -var "db_allocated_storage=${{ secrets.DB_ALLOCATED_STORAGE }}"
        working-directory: terraform

  docker-build:
    name: 'Build Docker Image'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t real-estate-app .

  app-test:
    name: 'FastAPI App Tests'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
